config/routes.rb
AlQuran::Application.routes.draw do
  devise_for :users

  resources :ayats, except: [:new, :destroy]
  resources :suras, except: [:new, :destroy]
  resources :paras, except: [:new, :destroy]
  resources :words, except: [:destroy]

  root to: "paras#index"

end

app/models/sura.rb
class Sura < ActiveRecord::Base
  belongs_to :para
  has_many :ayats
  has_many :word_frequencies, as: :wordable

  attr_accessible :name
end

app/controllers/suras_controller.rb
class SurasController < ApplicationController
  # GET /suras
  # GET /suras.json
  def index
    if params[:para_id]
      @para = Para.find params[:para_id]
      @suras = @para.suras
    end
    @suras = (@sura || Sura).paginate(per_page: 50, page: params[:page])


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @suras }
    end
  end

  # GET /suras/1
  # GET /suras/1.json
  def show
    @sura = Sura.find(params[:id])
    @ayats = @sura.ayats.paginate(per_page: 30, page: params[:page])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sura }
    end
  end

  # GET /suras/new
  # GET /suras/new.json
  def new
    @sura = Sura.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sura }
    end
  end

  # GET /suras/1/edit
  def edit
    @sura = Sura.find(params[:id])
  end

  # POST /suras
  # POST /suras.json
  def create
    @sura = Sura.new(params[:sura])

    respond_to do |format|
      if @sura.save
        format.html { redirect_to @sura, notice: 'Sura was successfully created.' }
        format.json { render json: @sura, status: :created, location: @sura }
      else
        format.html { render action: "new" }
        format.json { render json: @sura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /suras/1
  # PUT /suras/1.json
  def update
    @sura = Sura.find(params[:id])

    respond_to do |format|
      if @sura.update_attributes(params[:sura])
        format.html { redirect_to @sura, notice: 'Sura was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suras/1
  # DELETE /suras/1.json
  def destroy
    @sura = Sura.find(params[:id])
    @sura.destroy

    respond_to do |format|
      format.html { redirect_to suras_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/suras_helper.rb
module SurasHelper
end

app/views/suras/_form.html.erb
<%= form_for @sura, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :para_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :para_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                suras_path, :class => 'btn' %>
  </div>
<% end %>

app/views/suras/edit.html.erb
<%- model_class = Sura -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/suras/index.html.erb
<div class="page-header">
  <h1>Suras <%= current_para_name "For Para" %></h1>
</div>
<table class="table table-striped">
  <tr colspan="3">
    <%= will_paginate(@suras, :renderer => BootstrapPagination::Rails) %>
  </tr>
  <thead>
    <tr>
      <th>Sura number</th>
      <th>Sura name</th>
      <th>Ayats count</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @suras.each do |sura| %>

      <tr>
        <td><%= sura.id %></td>
        <td><%= sura.name %></td>
        <td><%= sura.ayats.size %></td>




        <td>
         <%= link_to "Show", sura_path(sura), :class => 'btn btn-primary', :title => "Open #{sura.name}" %>

         <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_sura_path(sura), :class => 'btn btn-mini' %>

        </td>
      </tr>
      <% end %>

  </tbody>

</table>
  <%= will_paginate(@suras, :renderer => BootstrapPagination::Rails) %>

app/views/suras/new.html.erb
<%- model_class = Sura -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/suras/show.html.erb
<%- model_class = Sura -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @sura.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:para_id) %>:</strong></dt>
  <dd><%= @sura.para_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              suras_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_sura_path(@sura), :class => 'btn' %>
</div>

<h3>Ayats for <%= @sura.name  %></h3>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Ayat number</th>
    <th>Urdu Translation</th>
  </tr>
  </thead>
  <tbody>
  <% @ayats.each do |ayat| %>
      <tr>
        <td><%= ayat.ayat_number %></td>
        <td title="<%=ayat.arabic_content%>"><%= ayat.content %></td>
        </td>
      </tr>
  <% end %>
  <tr colspan="3">
    <%= will_paginate(@ayats, :renderer => BootstrapPagination::Rails, url: sura_path(@sura)) %>
  </tr>
  </tbody>