config/routes.rb
AlQuran::Application.routes.draw do
  devise_for :users

  resources :ayats, except: [:new, :destroy]
  resources :suras, except: [:new, :destroy]
  resources :paras, except: [:new, :destroy]
  resources :words, except: [:destroy]

  root to: "paras#index"

end

app/models/para.rb
class Para < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/paras_controller.rb
class ParasController < ApplicationController
  # GET /paras
  # GET /paras.json
  def index
    @paras = Para.paginate(per_page: 10, page: params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @paras }
    end
  end

  # GET /paras/1
  # GET /paras/1.json
  def show
    @para = Para.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @para }
    end
  end

  # GET /paras/new
  # GET /paras/new.json
  def new
    @para = Para.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @para }
    end
  end

  # GET /paras/1/edit
  def edit
    @para = Para.find(params[:id])
  end

  # POST /paras
  # POST /paras.json
  def create
    @para = Para.new(params[:para])

    respond_to do |format|
      if @para.save
        format.html { redirect_to @para, notice: 'Para was successfully created.' }
        format.json { render json: @para, status: :created, location: @para }
      else
        format.html { render action: "new" }
        format.json { render json: @para.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /paras/1
  # PUT /paras/1.json
  def update
    @para = Para.find(params[:id])

    respond_to do |format|
      if @para.update_attributes(params[:para])
        format.html { redirect_to @para, notice: 'Para was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @para.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paras/1
  # DELETE /paras/1.json
  def destroy
    @para = Para.find(params[:id])
    @para.destroy

    respond_to do |format|
      format.html { redirect_to paras_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/paras_helper.rb
module ParasHelper
end

app/views/paras/_form.html.erb
<%= form_for @para, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                paras_path, :class => 'btn' %>
  </div>
<% end %>

app/views/paras/edit.html.erb
<%- model_class = Para -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/paras/index.html.erb
<%- model_class = Para -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Para number</th>
      <th>Name %></th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @paras.each do |para| %>
      <tr>
        <td><%= link_to para.id, para_path(para) %></td>
        <td><%= para.name %></td>
        <td>
          <%= link_to "show",para_path(para), :class => 'btn btn-primary' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_para_path(para), :class => 'btn btn-mini' %>

        </td>
      </tr>
    <% end %>
    <tr colspan="3">
      <%= will_paginate(@paras, :renderer => WillPaginate::ActionView::LinkRenderer) %>
    </tr>
  </tbody>
</table>

app/views/paras/new.html.erb
<%- model_class = Para -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/paras/show.html.erb
<%- model_class = Para -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @para.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              paras_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_para_path(@para), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              para_path(@para),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>