config/routes.rb
AlQuran::Application.routes.draw do
  devise_for :users

  resources :ayats, except: [:new, :destroy]
  resources :suras, except: [:new, :destroy]
  resources :paras, except: [:new, :destroy]
  resources :words, except: [:destroy]

  root to: "paras#index"

end

app/models/ayat.rb
class Ayat < ActiveRecord::Base
  belongs_to :sura
  has_many :word_frequencies, as: :wordable

  attr_accessible :ayat_number, :content, :sura_id, :arabic_content

  def para_name
    sura.para.name
  end

  def sura_name
    sura.name
  end

end

app/controllers/ayats_controller.rb
class AyatsController < ApplicationController
  # GET /ayats
  # GET /ayats.json
  def index
    if params[:sura_id]
      @sura = Sura.find params[:sura_id]
      @ayats = @sura.ayats
    end
    @ayats = (@ayats || Ayat).paginate(per_page: 50, page: params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ayats }
    end
  end

  # GET /ayats/1
  # GET /ayats/1.json
  def show
    @ayat = Ayat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ayat }
    end
  end

  # GET /ayats/new
  # GET /ayats/new.json
  def new
    @ayat = Ayat.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ayat }
    end
  end

  # GET /ayats/1/edit
  def edit
    @ayat = Ayat.find(params[:id])
  end

  # POST /ayats
  # POST /ayats.json
  def create
    @ayat = Ayat.new(params[:ayat])

    respond_to do |format|
      if @ayat.save
        format.html { redirect_to @ayat, notice: 'Ayat was successfully created.' }
        format.json { render json: @ayat, status: :created, location: @ayat }
      else
        format.html { render action: "new" }
        format.json { render json: @ayat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ayats/1
  # PUT /ayats/1.json
  def update
    @ayat = Ayat.find(params[:id])

    respond_to do |format|
      if @ayat.update_attributes(params[:ayat])
        format.html { redirect_to @ayat, notice: 'Ayat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ayat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ayats/1
  # DELETE /ayats/1.json
  def destroy
    @ayat = Ayat.find(params[:id])
    @ayat.destroy

    respond_to do |format|
      format.html { redirect_to ayats_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ayats_helper.rb
module AyatsHelper

end

app/views/ayats/_form.html.erb
<%= form_for @ayat, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :sura_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :sura_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :ayat_num, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :ayat_num, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                ayats_path, :class => 'btn' %>
  </div>
<% end %>

app/views/ayats/edit.html.erb
<%- model_class = Ayat -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ayats/index.html.erb
<div class="page-header">
  <h1>Ayats <%= current_sura_name "For Sura" %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Sura Name</th>
      <th>Urdu translation</th>

      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @ayats.each do |ayat| %>
      <tr>
        <td><%= link_to ayat.ayat_number, ayat_path(ayat) %></td>
        <td><%= ayat.sura_name %></td>
        <td><%= ayat.content %></td>
        <td>
          <%= link_to "Show", ayat_path(ayat), :class => 'btn btn-primary' %>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_ayat_path(ayat), :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
    <tr colspan="3">
      <%= will_paginate(@ayats, :renderer =>  BootstrapPagination::Rails) %>
    </tr>
  </tbody>
</table>

app/views/ayats/new.html.erb
<%- model_class = Ayat -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ayats/show.html.erb
<div class="page-header">
  <h1>Ayat <%= @ayat.id %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Sura name </strong></dt>
  <div><%= @ayat.sura_name %></div>


  <dt><strong>Ayat number </strong></dt>
  <div><%= @ayat.ayat_number %></div>

  <dt><strong>Urdu Content: </strong></dt>
  <div><%= @ayat.content %>:</strong></div>

  <dt><strong>Arabic Content: </strong></dt>
  <div><%= @ayat.arabic_content %>:</strong></div>

</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              ayats_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_ayat_path(@ayat), :class => 'btn' %>
  <div>