config/routes.rb
AlQuran::Application.routes.draw do
  devise_for :users

  resources :ayats, except: [:new, :destroy]
  resources :suras, except: [:new, :destroy]
  resources :paras, except: [:new, :destroy]
  resources :words, except: [:destroy]

  root to: "paras#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "AlQuran" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">AlQuran</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Para", paras_path  %></li>
              <li><%= link_to "Sura", suras_path  %></li>
              <li><%= link_to "Ayat", ayats_path  %></li>
              <li><%= link_to "Words Frequency", words_path  %></li>
              <li>
                <% if user_signed_in? %>
                 <%= link_to "Signout", destroy_user_session_path, method: :delete %>
                <%else%>
                    <%= link_to "Signin", new_user_session_path %>
                    <%end%>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">NOTE</li>
              <p>
                Please note that this is very first draft version of Al Quran. Used for demo purposes only and subject to change.

              </p>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <form class="form-search">
          <input type="text" class="input-medium search-query" placeholder="Search" >
          <button type="submit" class="btn">Search</button>
          </form>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>